### PR TITLE
Final changes for v1.1.0 

### PR DESCRIPTION
**Pull request by jackdevey**
Update build metadata

### CODE REVIEW

**Review by russellbanks — DISMISSED** [review]
LGTM

**Review by jackdevey — COMMENTED** [review]
Reverted as commit should not be on this branch as is a planned v1.2.0 feature

**Review by jackdevey — COMMENTED** [review]
Should be ready now, have x86 and x64 installers ready. What do you think @russellbanks?

**Comment by russellbanks** [comment]
Should our first chocolatey release be v1.1.0, do you think?

**Review by russellbanks — APPROVED** [review]

**Pull request merged**
