### PR TITLE
Create CODEOWNERS file

### PR DESCRIPTION
**Pull request by jackdevey**
Structure the repo in a much better way. All PRs featuring changes to the dirs and files will require approval from the code owner

### CODE REVIEW

**Comment by jackdevey** [comment]
I did delete the wrong file but it was an unused one anyway so im doing you a favor here :)

**Review by russellbanks — CHANGES_REQUESTED** [review]
I'm happy to manage the dependencies if you'd like :)

**Comment by jackdevey** [comment]
Okay sure

**Review by russellbanks — APPROVED** [review]
LGTM

**Pull request merged**
